### ISSUE TITLE
Unable to deploy application 

### ISSUE THREAD

**Issue by KopilDev1990** [aws-amplify/amplify-backend#1456]
### Environment information

```plain text
-----
```

### Description

Failed to deploy. React application on amplify from Github and also if we use Zip to deploy it. 
its having this error anyways. 
<img width="1677" alt="Screenshot 2024-05-08 at 3 50 06 AM" src="https://github.com/aws-amplify/amplify-backend/assets/168790539/c573997e-c6f0-491f-9c3f-ce647e22500e">
Need to fix this as soon as possible.

**Comment by swaminator** [comment]
@KopilDev1990 are you using manual deploys?

**Comment by Jay2113** [comment]
@KopilDev1990 can you please share your account id privately via a DM on our [community discord server](https://discord.gg/amplify)? My username is `Jay Raval`.

**Comment by Jay2113** [comment]
@KopilDev1990 the root cause seems related to an account level issue and as next steps, we recommend reaching out to [AWS Support](https://support.console.aws.amazon.com/support/home).
- If you have a premium support plan, you can open a support case under the `Technical` section using the following information:
  - Service: Amplify Console
  - Category: Other
  - Severity: General guidance
  - Subject line: `Check Account Status - Amplify Hosting`
  - Describe the issue you are experiencing for example: `Unable to create app`
- If you do not have a paid support plan and instead see a basic support plan in the AWS support console, you can open a support case under `Account and Billing` section using the following information:
  - Service: Account
  - Category: Other Account Issues
  - Severity: General Question
  - Subject line: `Check Account Status - Amplify Hosting`
  - Describe the issue you are experiencing for example: `Unable to create app`

Do link the GitHub issue to the support ticket to help track the issue. Thanks! 

Lastly, we are working on improving the error messaging for such issues and are tracking it here: https://github.com/aws-amplify/amplify-backend/issues/1287#issuecomment-2077753079

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out if you require any further assistance.

**Comment by GabrielAmazonas** [comment]
I have the same issue. Any updates? @Jay2113
