### ISSUE TITLE
Unable to deploy an application

### ISSUE THREAD

**Issue by aurobindobhuyan** [aws-amplify/amplify-backend#1462]
### Environment information

```plain text
Operating System: Windows 10
Browser: Google Chrome
File Types Uploaded: HTML, CSS, JavaScript (Contained in a zip file)
File Sizes: 400MB
Error Message: Error: Build failed, you have reached the maximum number of apps in this account.
Screenshot: Attached
Detailed Description: Attempted to drag and drop files for a new project setup. The upload completes, but the build process fails with the above error.
```

### Description

When I was creating a new app in AWS Amplify, it showed: Build failed, you have reached the maximum number of apps in this account. However, I have only one application running in this account; this is the second app I want to host here.

![Screenshot 2024-05-08 151120](https://github.com/aws-amplify/amplify-backend/assets/100915096/fddb407a-5b34-4351-bbde-198277ef54ad)

![Screenshot 2024-05-08 145610](https://github.com/aws-amplify/amplify-backend/assets/100915096/fd7b8491-9bf5-4249-a655-8424a435e5c3)

**Comment by Jay2113** [comment]
@aurobindobhuyan 👋 , thanks for reaching out. Can you please share your account id privately via a DM on our [community discord server](https://discord.gg/amplify)? My username is `Jay Raval`.

**Comment by aurobindobhuyan** [comment]
@Jay2113 I've sent you my account id in the discord. Please have a look at it.

**Comment by Jay2113** [comment]
@aurobindobhuyan the root cause seems related to an account level issue and as next steps, we recommend reaching out to [AWS Support](https://support.console.aws.amazon.com/support/home).
- If you have a premium support plan, you can open a support case under the `Technical` section using the following information:
  - Service: Amplify Console
  - Category: Other
  - Severity: General guidance
  - Subject line: `Check Account Status - Amplify Hosting`
  - Describe the issue you are experiencing for example: `Unable to create app`
- If you do not have a paid support plan and instead see a basic support plan in the AWS support console, you can open a support case under `Account and Billing` section using the following information:
  - Service: Account
  - Category: Other Account Issues
  - Severity: General Question
  - Subject line: `Check Account Status - Amplify Hosting`
  - Describe the issue you are experiencing for example: `Unable to create app`

Do link the GitHub issue to the support ticket to help track the issue. Thanks! 

Lastly, we are working on improving the error messaging for such issues and are tracking it here: https://github.com/aws-amplify/amplify-backend/issues/1287#issuecomment-2077753079

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out if you require any further assistance.

**Comment by aurobindobhuyan** [comment]
I've opened a support case with AWS to address the underlying account issue. The details are as follows:
- **AWS Support Case ID:** 171531687900962
- **Subject:** Check Account Status - Amplify Hosting
- **Status:** Resolved
