### ISSUE TITLE
support adding environment variables with `addEnvironment` on `backend.myFunction`

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-backend#1553]
### Environment information

```plain text
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 185.98 MB / 32.00 GB
  Shell: /opt/homebrew/bin/fish
Binaries:
  Node: 20.12.2 - ~/Library/Caches/fnm_multishells/28073_1716560750829/bin/node
  Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/28073_1716560750829/bin/yarn
  npm: 10.5.0 - ~/Library/Caches/fnm_multishells/28073_1716560750829/bin/npm
  pnpm: 9.1.2 - ~/Library/Caches/fnm_multishells/28073_1716560750829/bin/pnpm
NPM Packages:
  @aws-amplify/backend: 1.0.2
  @aws-amplify/backend-cli: 1.0.3
  aws-amplify: 6.3.4
  aws-cdk: 2.143.0
  aws-cdk-lib: 2.143.0
  typescript: 5.4.5
AWS environment variables:
  AWS_PROFILE = josef-gen2
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

when adding custom CDK resource data (or info from another Amplify resource) to a function's environment, it would be nice to reference it with the typed `env`. Similar to [`addEnvironment`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.Function.html#addwbrenvironmentkey-value-options):

```ts
import { defineBackend } from "@aws-amplify/backend"
import { myFunction } from "./functions/my-function/resource"

const backend = defineBackend({ myFunction })

backend.myFunction.addEnvironment("key", "value")
```

**Comment by naedx** [comment]
I'm also interested in this solution.

My use case is that I have a Lambda function that I want to access my AppSync API. Amplify allows me to link the two with `a.schema({..}).authorization(allow => [allow.resource(myLambda).to('mutate')])`. This would provide (1) the IAM authorization necessary and (2) the endpoint URL to the function. I don't want to use this way because I don't want my function to be authorized on all models. I want to target only a specific field. 

As a result I need to provide both the permissions and the endpoint url manually. I'm using the env variables for the latter.

**Comment by ykethan** [comment]
Closing the issue as https://github.com/aws-amplify/amplify-backend/pull/1711 has been merged.
