### ISSUE TITLE
Custom domain stuck on SSL configuration

### ISSUE THREAD

**Issue by sujan-s** [aws-amplify/amplify-backend#1716]
### Environment information

```plain text
No idea what this is
```

### Description

I have a domain and a hosted zone on Route53. I have an Amplify app for which I’m trying to set up a custom domain. Been a few days, and multiple tries later, it’s always stuck at the SSL config step. I have the CNAME entries setup, but it never progresses.

I’m doing all this on the web UI, nothing via the CLI.

I’ve also tried setting up a manual certificate via ACM, but that’s also always stuck at the Pending validation state.

How can I fix this?

![image](https://github.com/aws-amplify/amplify-backend/assets/19920532/0688ab32-0ec8-4c86-8575-e98898631703)

**Comment by Jay2113** [comment]
Hi @sujan-s 👋 , thanks for reaching out. Can you share the following information:
- Are you using a private Route 53 hosted zone? Currently, Amplify Hosting only supports public hosted zones.
- When using the Amplify managed certificate during the domain activation process, were the CNAME records (ACM server validation and CloudFront distribution) added to your hosted zone?
- Can you share a screenshot of the domain configuration in the Amplify console?

**Comment by sujan-s** [comment]
Hiya @Jay2113!

- Yup, it’s a public zone
- Yes, they were added, and after it failed the first couple of tries, I tried deleting the records and adding them manually, that didn’t work either.
- Here’s the screenshot
![Screenshot 2024-07-09 at 11 16 49 AM](https://github.com/aws-amplify/amplify-backend/assets/19920532/83fd7d4c-ceee-466c-8369-3fc38a0592b8)

**Comment by Jay2113** [comment]
@sujan-s thanks for sharing those details. Can you also share your Amplify app id?

**Comment by sujan-s** [comment]
`dwmip6xohr9gr`

Here you go

**Comment by zvs96** [comment]
The same problem.
My app id: d3kzar1cxcp3l4

**Comment by sujan-s** [comment]
Any luck, @Jay2113?

**Comment by zvs96** [comment]
> Any luck, @Jay2113?

You can cancel and try again.
For me Its halped.

**Comment by sujan-s** [comment]
@zvs96 I’ve tried about a dozen times by now, ha. :)

**Comment by Jay2113** [comment]
Hi @sujan-s, we are continuing to investigate into it. In the meantime, from our internal logs we observed the request to add a ACM server validation CNAME record (`acm-validations.aws.`) to Route 53 was successful. Can you please reverify if that records gets added to the hosted zone?

**Comment by sujan-s** [comment]
@Jay2113 I’ve tried that too—but the cert is then stuck at the Pending validation state, as I’ve mentioned in the original issue.

The CNAME records getting added in Route53 is NOT THE ISSUE. They get added regardless of AMplify-managed cert, or adding a cert via ACM manually. The entries get added successfully in both approaches.

The issue is that **_it doesn’t progress further_**.

- Amplify managed: Stuck on SSL config
- ACM: Cert stuck on Pending validation, can’t see the cert inside Amplify.

![Screenshot 2024-07-13 at 8 00 21 AM](https://github.com/user-attachments/assets/b730cb78-2d7b-47fa-9b78-3ad0af421f67)

Come on guys, I’m just repeating the same thing again. Let me know if you need more info, happy to provide.

**Comment by sujan-s** [comment]
I’ve tried this whole delete-retry-delete-retry steps in multiple combinations for a week now. Even deleting the entire hosted zone and creating another from scratch didn’t help.

This should all be one-click setups, IMHO—it’s just Amplify and Route53 talking to each other.

**Comment by Jay2113** [comment]
Thank you for confirming the CNAME record. Since your setup involves Route 53, the domain activation process should be a one-click operation, as the service automatically adds the necessary records to your Route 53 hosted zone on your behalf. We are currently investigating this issue and will provide updates on this thread as soon as we have more information.

**Comment by Jay2113** [comment]
Hi @sujan-s, thanks for your continued cooperation. Based on the information provided, we did some investigation on our end and it appears that the potential root cause might be related to the domain configuration within Route 53. 

As mentioned in your previous comment, the ACM certificate status is showing as `Pending validation`, which could be indicative of an issue with the DNS validation process. This troubleshooting [document](https://docs.aws.amazon.com/acm/latest/userguide/troubleshooting-DNS-validation.html) outlines common causes for it. Our recommendation would be to review the guide and this [article](https://repost.aws/knowledge-center/route-53-validate-acm-certificates) to ensure that the ACM certificate can be provisioned successfully when using Route 53. Once the ACM certificate is provisioned, you can attempt the domain activation process in Amplify and observe if the issue persists.

If the issue persists after following the troubleshooting guide, we would be happy to schedule a call with you to discuss this further.

**Comment by sujan-s** [comment]
Ok sweet, let me try this later today and get back to you folks ✌🏽

**Comment by sujan-s** [comment]
@Jay2113 That didn’t work. Neither the ACM approach, nor the Amplify managed one. Tried removing the underscore/trailing period in both cases, but nothing changed.

However, I noticed another error message—
![Screenshot](https://github.com/user-attachments/assets/663b7f52-06f9-4c0f-9a32-b15486cd742f)

Does this have any bearing on this?

**Comment by Jay2113** [comment]
@sujan-s The error in the screenshot is likely due to an extended Amplify console session and can be resolved by refreshing the page.

Since the ACM certificate is stuck with a `Pending validation` status, I recommend reaching out to [AWS technical support](https://docs.aws.amazon.com/awssupport/latest/user/case-management.html#creating-a-support-case) as they can assist with debugging and troubleshooting issues related to your Route 53 and ACM setup. Once the certificate is successfully provisioned and validated, try to recreate the domain association in Amplify. If the issue persists, we can schedule a call for further discussion.

**Comment by sujan-s** [comment]
Ideally, I don’t want to go the manual ACM route, that’s just extra overhead. I was only trying that as a last resort.

I would want to use the Amplify-managed route—which should work with no hoop-jumping from my side. How can we get there?

**Comment by Jay2113** [comment]
@sujan-s We would like to schedule a call with you. Can you share your availability via a DM on our [community discord server](https://discord.gg/amplify)?. My username is `Jay Raval`.

**Comment by sujan-s** [comment]
@Jay2113 Thanks for finding the root cause!

For those in the future: the reason this wasn’t working was because of name servers not added to the registered domain. It’s not enough to have it in just the Hosted Zone, you gotta add it in the registered domain as well.

**Comment by Maclenn77** [comment]
> @Jay2113 Thanks for finding the root cause!
> 
> For those in the future: the reason this wasn’t working was because of name servers not added to the registered domain. It’s not enough to have it in just the Hosted Zone, you gotta add it in the registered domain as well.

Where do you add that? In the hosted zone of you main domain?

**Comment by mihaimatraguna** [comment]
> Where do you add that? In the hosted zone of you main domain? Facing same problem with custom domain using a subdomain.

@Maclenn77  Let's assume that we have the main domain `example.com` added in Route53 as a hosted zone and a subdomain called `aa.example.com` also added as a hosted zone in Route53. 

You need to copy the NS from the subdomain (`aa` in our case) and put them as a NS record in the main domain.

**Comment by Maclenn77** [comment]
Thanks @mihaimatraguna 
 
 Just a specification that was counter-intuitive for me: When copying NS, include the points at the end. I was removing when I added them to main domain, and it seems that it fails for that reason
 
``` 
ns-example.com. # Correct
ns-other-example.com. #Correct
ns-badexample.com # Incorrect
```

**Comment by ohampro** [comment]
I’m facing the same problem with Custom domains. I purchased my domain from Domain.com and updated its NS records to the four NS provided in the Hosted Zone. Amplify detected the domain, and I proceeded with the one-click setup. However, it’s stuck at the SSL configuration step, displaying the message: 'Adding subdomain records to your DNS provider...

Appreciate any ideas!

**Comment by tawoyinfa** [comment]
@ohampro did you get this resolved ? I have  exactly the same problem you described

**Comment by ohampro** [comment]
Hi @tawoyinfa, yes, I managed to resolve the issue! Here’s what worked for me:

1. During the Amplify "Add Domain" setup, it automatically creates both the root domain (example.com) and the www subdomain.
2. I removed the www subdomain from the setup and proceeded with only the root domain. The process completed quickly.
3. Once the root domain was successfully added, I manually added the www subdomain separately. (took more time to complete)


_I first verified NS propagation using [DNS Checker](https://dnschecker.org/), which showed that the root domain was mostly propagated, while the www subdomain was incomplete. Separating the creation of the www subdomain proved helpful and resolved the issue._

Let me know if this helps!

**Comment by ntanh3108** [comment]
> Thanks [@mihaimatraguna](https://github.com/mihaimatraguna)
> 
> Just a specification that was counter-intuitive for me: When copying NS, include the points at the end. I was removing when I added them to main domain, and it seems that it fails for that reason
> 
> ```
> ns-example.com. # Correct
> ns-other-example.com. #Correct
> ns-badexample.com # Incorrect
> ```

Hi @Maclenn77, I tried putting a period at the end, but maybe AWS did't allow me to do that. Have you tried it and succeeded?

**Comment by cmfraser1380** [comment]
A note to those coming to this thread as of May, 2025: see the [final comment](https://github.com/aws-amplify/amplify-backend/issues/1716#issuecomment-2250925423) that @sujan-s added on Jul 25, 2024. Also, as @ntanh3108 noted, including the trailing dot for a name server (`ns-example.com.`) will generate an error—when adding the name server under **Route 53 > Registered domains > example.com > Details > Name servers** in the AWS Management console. Removing the trailing dot (`ns-example.com`) when entering the name server removes the error (provided the name-server entry is otherwise well formed). Hope that helps. Wasted quite a bit of time on this before I came across the [solution](https://github.com/aws-amplify/amplify-backend/issues/1716#issuecomment-2250925423) that @sujan-s posted. Also noteworthy that the "stuck on SSL configuration" issue is still an issue almost a year later—no helpful notifications and/or explanations have been added to the Amplify console, and no official AWS post has been added to this thread providing guidance. [This section](https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-custom-domains.html#my-domain-hosted-with-amazon-route-53-is-stuck-in-the-pending-verification-state) on the [Troubleshooting custom domains](https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-custom-domains.html) suggests that the issue "is possible".

**Comment by bilal-korir** [comment]
This is how we solved it in our case:

- **The short answer:** 

In our case, the cause was that the servers found at **Route 53 > Registered domains > mywebsite.com > Name servers** section were not correct. The solution is to update the name servers to match the ones found at **Route 53 > Hosted zones > mywebsite.com > NS** record. Exactly as @sujan-s and @Jay2113 mentioned in their comment.

- **A more elaborate answer:**

1. Navigate to **Route 53 > Hosted zones**.

![Image](https://github.com/user-attachments/assets/a3b83e1c-a3ad-4099-8a8d-cffcd26a3ad3)

2. Create a **public** hosted zone (if you don’t have one already).

![Image](https://github.com/user-attachments/assets/985a4f11-f10f-415d-8454-e90dec0cb8e5)

3. Copy the Name Servers shown under the **NS** record (these are generated and added automatically for you by Route 53 when you create a hosted zone).

![Image](https://github.com/user-attachments/assets/777bb2bf-ec98-4803-a5c8-a6de92560f9a)

4. Navigate to **Route 53 > Registered domains > mywebsite.com**, and click on **“Actions”,** then select **“Edit name servers”**.

![Image](https://github.com/user-attachments/assets/6e2e2c1a-874d-47a6-bb2e-2c466ce854a6)

5. Enter the Name Servers that Route 53 created for you earlier (NS record). Copy and paste without the trailing dot (.).

![Image](https://github.com/user-attachments/assets/ff84e72d-14ee-4058-ae3d-a521c2bb8300)

6. Navigate to **AWS Amplify > myAmplifyApp > Hosting > Custom domain**, and add the domain again.

![Image](https://github.com/user-attachments/assets/15a11aac-47e6-493c-98e3-040394ba73dc)

- **Notes**

1. Before applying the steps above, we deleted the associated domain from the Amplify app's console, found at: **AWS Amplify > myAmplifyApp > Hosting > Custom domain > mywebsite.com > Actions > Delete domain**. I think it’s best to apply this step to start a clean setup.

2. Before applying the steps above, we deleted the hosted zone and created a fresh one. **_It’s not necessary to apply this step, but if you like a clean setup, you can do it._**

3. While going from one step to another, try to wait a few minutes between each step. DNS records for a domain and email setup sometimes take time.

4. There is a useful troubleshooting link from AWS that mentions this issue: [My domain hosted with Amazon Route 53 is stuck in the Pending Verification state
](https://docs.aws.amazon.com/amplify/latest/userguide/troubleshooting-custom-domains.html#my-domain-hosted-with-amazon-route-53-is-stuck-in-the-pending-verification-state)

**Comment by cmfraser1380** [comment]
Way to go, @bilal-korir.

**Comment by jrhager84** [comment]
> Hi [@tawoyinfa](https://github.com/tawoyinfa), yes, I managed to resolve the issue! Here’s what worked for me:
> 
> 1. During the Amplify "Add Domain" setup, it automatically creates both the root domain (example.com) and the www subdomain.
> 2. I removed the www subdomain from the setup and proceeded with only the root domain. The process completed quickly.
> 3. Once the root domain was successfully added, I manually added the www subdomain separately. (took more time to complete)
> 
> _I first verified NS propagation using [DNS Checker](https://dnschecker.org/), which showed that the root domain was mostly propagated, while the www subdomain was incomplete. Separating the creation of the www subdomain proved helpful and resolved the issue._
> 
> Let me know if this helps!

Removing the www subdomain is what fixed it for me. I was pulling my hair out for DAYS. Thanks!
