### ISSUE TITLE
A group with the name already exists

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-backend#1781]
### Environment information

```plain text
System:
  OS: macOS 14.5
  CPU: (8) arm64 Apple M1
  Memory: 229.23 MB / 16.00 GB
  Shell: /opt/homebrew/bin/fish
Binaries:
  Node: 20.11.1 - ~/.local/share/nvm/v20.11.1/bin/node
  Yarn: 1.22.19 - ~/.local/share/nvm/v20.11.1/bin/yarn
  npm: 10.8.2 - ~/Documents/ampapps/backenddevtest/amplify-next-pages-template/node_modules/.bin/npm
  pnpm: 9.4.0 - ~/Library/pnpm/pnpm
NPM Packages:
  @aws-amplify/backend: 1.0.4
  @aws-amplify/backend-cli: 1.2.0
  aws-amplify: 6.4.3
  aws-cdk: 2.150.0
  aws-cdk-lib: 2.150.0
  typescript: 5.5.4
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

When modifying the Auth groups from 
`groups: [“VIEWERS”, “ADMINS”, “MODERATORS”]` -> `groups: [“Admins”, “Managers”, “Users”],`
causes 

<img width="747" alt="image" src="https://github.com/user-attachments/assets/d0e5d5d9-4888-4d6b-a369-ba2e89628ca3">

**Comment by josefaidt** [comment]
marking as a dependency bug

**Comment by awsluja** [comment]
changing the casing of a group will lead to this error, same issue in gen1 https://github.com/aws-amplify/amplify-cli/issues/13103

**Comment by awsluja** [comment]
The problem here is that you cannot create a duplicate group "ADMINS" & "Admins" during the update process, given that group names are case-insensitive.

Any attempt to modify the casing of a group requires first deleting that group altogether, this is because Cloudformation uses [_replacement_ for the GroupName property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpoolgroup.html#cfn-cognito-userpoolgroup-groupname). It will first create the replacement group and change the references from other dependent resources to point to the replacement group, and then deletes the old group. This will fail because it can't create the replacement group with a duplicate name.
