### ISSUE TITLE
Build Failed: no error / build error 

### ISSUE THREAD

**Issue by hongthach12** [aws-amplify/amplify-backend#1931]
### Environment information

```plain text
none
```

### Describe the bug

i don't know why amplify build failure because amplify deployment no return any error

app ID: d25lcp98a9a3aw
branch: staging

### Reproduction steps

none

**Comment by Nithipongrobolingo** [comment]
I found the same issue. !!

<img width="952" alt="image" src="https://github.com/user-attachments/assets/b7e0a3f6-5290-4153-a176-57724e9ac698">

**Comment by oscar-iolab** [comment]
I am having the same issue, using NextJS.
The deployment showing failed without any error statement, just empty log.

Then attempted to redeploy other app which having successful build before (last week, 22nd Aug), but the new build failed, so something is wrong with the deployment process.

Region: ap-southeast-1 Singapore

PS. Had tried to reconnect branch but still the same.

**Comment by Jay2113** [comment]
Between 1:36 AM and 2:58 AM PST, AWS Amplify Hosting experienced increased API error rates in the AP-NORTHEAST-1, AP-EAST-1, US-WEST-2, and AP-SOUTHEAST-1 Regions. The issue has been resolved and the service is operating normally.

Additionally, please note that whenever we have customer impact due to issues like this, we post updates to your Personal Health Dashboard (PHD): https://aws.amazon.com/premiumsupport/technology/aws-health/.

**Comment by calavera** [comment]
You can also find more information about this recent event in the AWS Health Dashboard: https://health.aws.amazon.com/health/status

**Comment by Jay2113** [comment]
Closing this thread since the issue has been resolved.
