### ISSUE TITLE
Deployment not showing new code for existing branches

### ISSUE THREAD

**Issue by chrowe** [aws-amplify/amplify-backend#1996]
### Environment information

```plain text
https://main.d2yfr6uk327l7n.amplifyapp.com/
```

### Describe the bug

After I push code to the branch that already had code on it, I don't see the updates. If I create a new branch, it works fine.

### Reproduction steps

Deploy code to a branch.
Deploy some more code.

**Comment by ykethan** [comment]
Hey @chrowe, under the `App setting` -> `Branch setting` on selecting `Reconnect repository` and trigger a new commit does this start the build?

**Comment by chrowe** [comment]
I should have said that the build happens, but the site does not show the updates.

**Comment by Jay2113** [comment]
@chrowe Amplify Hosting supports instant cache invalidation after a deployment and thus you should be able to deploy updates to your application immediately without waiting for CloudFront CDN cache to expire or manually invalidating it. Here's a way you can verify whether the application has been updated per the latest deployed changes:
- Review the last updated timestamp for the branch in the Amplify console
- Access the website/URL and inspect the `Network` tab in the browser's developer console
- Review the last modified timestamp for the assets (js,css or image files)
- Both the last modified and last updated timestamp for the branch should match thereby indicating the latest changes have been deployed.

<img width="998" alt="Screenshot 2024-09-20 at 10 48 08 AM" src="https://github.com/user-attachments/assets/51d2f169-1a0e-4934-8597-abe509b81e50">

---

I am going to close this thread since the application is working as expected but feel free to reopen if you are still running into this issue. Thanks!
