### ISSUE TITLE
Can't see any created resources; Stack does not exist.

### ISSUE THREAD

**Issue by sshvaiko** [aws-amplify/amplify-backend#2037]
### Environment information

```plain text
n/a
```

### Describe the bug

Hello! I deployed two simple NextJS project on Amplify [using this manual](https://docs.aws.amazon.com/amplify/latest/userguide/deploy-nextjs-app.html). Both projects are up and running, but for some reason I can't see any creates resources, such as Lambda functions. When I go to my deployment, "Deployed backend resources" I see nothing and when I click Download amplify_outputs.json I see this error:
Stack does not exist.

I googled, it looks like something is wrong with region and I can't figure out how to fix that.

### Reproduction steps

1) Deploy NextJS project
2) Click "Deployed backend resources"

**Comment by Jay2113** [comment]
Hi @sshvaiko 👋 , thanks for raising this! The manual that you have linked to outlines steps for deploying a Next.js SSR frontend application and since Amplify Hosting manages the resources required to deploy the app those resources aren't visible in the console under the `Deployed backend resources` section.

The `Deployed backend resources` section will only list the backend resources for the app that are created in your AWS account. Additionally, you can learn more about the `amplify_outputs` file here: https://docs.amplify.aws/react/reference/amplify_outputs/.

**Comment by sshvaiko** [comment]
Hi @Jay2113, thanks for your answer! But how the app is deployed in the end? What AWS services are used to deploy API routers, front-end?

**Comment by Jay2113** [comment]
Hi @sshvaiko, when you deploy a Next.js SSR frontend application on Amplify Hosting, the service creates the following resources:
- A CloudFront distribution to serve and distribute your web app globally.
- Object storage to store your build artifacts.
- Serverless compute functions to serve requests from your API and handle SSR requests.

Since Amplify Hosting provides a [fully managed hosting infrastructure](https://aws.amazon.com/blogs/mobile/amplify-next-js-13/), these resources are not created in your AWS account. Instead, they are provisioned and managed by the service. As a result, you won't observe any new CloudFormation stacks or other resources in your AWS account.

**Comment by sshvaiko** [comment]
Great! Thank you very much for explanation.
