### ISSUE TITLE
referenceAuth capability does not work with latest amplify version?

### ISSUE THREAD

**Issue by Catazza** [aws-amplify/amplify-backend#2287]
### Environment information

```plain text
System:
  OS: macOS 13.6.3
  CPU: (10) arm64 Apple M1 Max
  Memory: 456.33 MB / 32.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.3.0 - ~/.nvm/versions/node/v20.3.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v20.3.0/bin/yarn
  npm: 9.6.7 - ~/.nvm/versions/node/v20.3.0/bin/npm
  pnpm: 9.5.0 - ~/.nvm/versions/node/v20.3.0/bin/pnpm
NPM Packages:
  @aws-amplify/backend: 1.8.0
  @aws-amplify/backend-cli: 1.0.4
  aws-amplify: 6.10.0
  aws-cdk: 2.146.0
  aws-cdk-lib: 2.171.1
  typescript: 5.3.3
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Describe the bug

I am following the docs [here](https://docs.amplify.aws/react-native/build-a-backend/auth/use-existing-cognito-resources/), I hope I have not missed anything!

I have an externally-generated user pool that I need to import into my CDK app. I have this definition in my resource.ts file for the auth backend.

When I run `npx ampx sandbox` I get the error:
```bash
amplify/backend.ts(21,26): error TS2339: Property 'cfnResources' does not exist on type 'ReferenceAuthResources'.
TypeScript validation check failed.
Resolution: Fix the syntax and type errors in your backend definition.
```

### Reproduction steps

My auth backend file is identical to the one in the docs, with the variables such as poolID populated.

```js
import { referenceAuth } from '@aws-amplify/backend';

export const auth = referenceAuth({
  userPoolId: 'us-east-1_xxxx',
  identityPoolId: 'us-east-1:b57b7c3b-9c95-43e4-9266-xxxx',
  authRoleArn: 'arn:aws:iam::xxxx:role/amplify-xxxx-mai-amplifyAuthauthenticatedU-xxxx',
  unauthRoleArn: 'arn:aws:iam::xxxx:role/amplify-xxxx-mai-amplifyAuthunauthenticate-xxxx',
  userPoolClientId: 'xxxx',
});
```

**Comment by ykethan** [comment]
Hey @Catazza, thank you for reaching. Tried reproducing but did not observe this error message on a sandbox deploy. 
But did notice `@aws-amplify/backend-cli: 1.0.4` does appear to be put of date. Could you try upgrading this to the latest(`1.4.2`) version and restart sandbox using `--debug` flag?
Additionally, on the `backend.ts` file is the auth resources being overridden?

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Do reach out to us if you are still experiencing this issue

**Comment by orgtom78** [comment]
am getting the same error: 

TypeScript validation check failed.
Caused By: amplify/backend.ts(17,9): error TS2339: Property 'cfnResources' does not exist on type 'ReferenceAuthResources'.

Resolution: Fix the syntax and type errors in your backend definition.

with the following backend.ts file:

`import { defineBackend } from '@aws-amplify/backend'

import { auth } from './auth/resource'

import { data } from './data/resource'

/**
 * @see https://docs.amplify.aws/react/build-a-backend/ to add storage, functions, and more
 */
export const backend = defineBackend({
  auth,
  data
})

const { cfnResources } = backend.auth.resources
const { cfnUserPool, cfnUserPoolClient } = cfnResources

cfnUserPool.addPropertyOverride('Policies.SignInPolicy.AllowedFirstAuthFactors', [
  'PASSWORD',
  'WEB_AUTHN',
  'EMAIL_OTP',
  'SMS_OTP'
])

cfnUserPoolClient.explicitAuthFlows = ['ALLOW_REFRESH_TOKEN_AUTH', 'ALLOW_USER_AUTH']

/* Needed for WebAuthn */
cfnUserPool.addPropertyOverride('WebAuthnRelyingPartyID', '<RELYING_PARTY>')
cfnUserPool.addPropertyOverride('WebAuthnUserVerification', 'preferred')

const externalDataSourcesStack = backend.createStack('MyExternalDataSources')`

**Comment by orgtom78** [comment]
would appreciate it if you could reopen the issue: 
my auth/resource.ts is:
```
import { referenceAuth } from '@aws-amplify/backend'

export const auth = referenceAuth({
  userPoolId: 'us-east-2_',
  identityPoolId: 'us-east-2:,
  authRoleArn: 'arn:aws:iam::authRole',
  unauthRoleArn: 'arn:aws:iam:unauthRole',
  userPoolClientId: '...'
})
```

**Comment by ykethan** [comment]
Hey @orgtom78, thanks you for the information. The configuration of your referenced resources cannot be modified on the Amplify backend. The configuration will need to updated on the Cognito resources directly via the AWS console or the entity managing the resource. 
Refer to the document providing this information: https://docs.amplify.aws/react/build-a-backend/auth/use-existing-cognito-resources/#use-auth-resources-with-an-amplify-backend

**Comment by orgtom78** [comment]
Thanks a lot for your prompt response. I was afraid that this is the case. Once I update the Cognito resource and run the npx ampx sandbox, the amplify output won’t update accordingly to reflect the Email OTP settings. Expected behavior? Can confirm that the logic works on the hosted UI. Need to configure the auth resource manually as documented here in the frontend? https://docs.amplify.aws/nextjs/build-a-backend/auth/use-existing-cognito-resources/

**Comment by ykethan** [comment]
Hey @orgtom78, thank you for the information. I was able to reproduce the issue on the Amplify outputs generation and opened a new issue for tracking this behavior: https://github.com/aws-amplify/amplify-backend/issues/2488

Currently, amplify backend does not yet support generating Email MFA configuration on the outputs file yet. 
this is currently being tracked on https://github.com/aws-amplify/amplify-backend/issues/2159

But the support for Email MFA was recently added our Amplify JS library, refer to the documentation providing this information
https://docs.amplify.aws/nextjs/build-a-backend/auth/concepts/multi-factor-authentication/#multi-factor-authentication-with-email
Additionally, feature request to support this on the Authenticator component: https://github.com/aws-amplify/amplify-ui/issues/5829

**Comment by orgtom78** [comment]
Hey @ykethan , thanks a lot for your feedback and additional information - very helpful!

Out of curiosity, I just went through the setup as described here: https://docs.amplify.aws/nextjs/build-a-backend/auth/modify-resources-with-cdk/#override-cognito-userpool-to-enable-passwordless-sign-in-methods with a new cognito resource but am still getting some errors. Will open a new issue for this one. 

Thanks again and hope passwordless methods for existing cognito resources will be seamlessly integrated into future amplify versions.
