### ISSUE TITLE
Refactor code to support various Package Managers

### ISSUE THREAD

**Issue by 0618** [aws-amplify/amplify-backend#517]
tl;dr: to refactor https://github.com/aws-amplify/samsara-cli/pull/507

https://github.com/aws-amplify/samsara-cli/pull/507 is a walk-around for us to implement workflow test for Package Managers. 
Once we are able to test them, we should refactor the code and implement the support in a proper way.

**Comment by brandoncroberts** [comment]
To Solve The issues like the one you mention here
<img width="748" alt="Screenshot 2024-01-04 at 12 28 32" src="https://github.com/aws-amplify/amplify-backend/assets/34548660/7c19fa70-2da7-4faf-8ae3-04ce4ab7975d">
I might recommend you consider to have the users install aws-cdk-lib / contructs in addition to the aws-amplify package, instead of including it as a peerDep.
It's similar to what chakra-ui does for example.
<img width="1440" alt="Screenshot 2024-01-04 at 10 45 09" src="https://github.com/aws-amplify/amplify-backend/assets/34548660/dc7eb701-cbbb-4a7d-87bc-180ad7a02d75">


Alternatively, if aws-cdk-lib / contructs are in fact installed as peerDeps, users technically don't need to install the library again, they should just be able to import from it/ use since it's installed as a peerDep.
So you could mention in the docs that users don't need to install these libs.

Personally, I prefer the ChakraUI approach, because importing from/ using a package one hasn't explicitly installed seems problematic.

**Comment by brandoncroberts** [comment]
To Solve The issues like the one you mention here
https://docs.amplify.aws/gen2/build-a-backend/add-aws-services/custom-resources/
<img width="748" alt="Screenshot 2024-01-04 at 12 28 32" src="https://github.com/aws-amplify/amplify-backend/assets/34548660/7c19fa70-2da7-4faf-8ae3-04ce4ab7975d">
I might recommend you consider to have the users install aws-cdk-lib / contructs in addition to the aws-amplify package, instead of including it as a peerDep.
It's similar to what chakra-ui does for example.
<img width="1109" alt="Screenshot 2024-01-04 at 12 26 44" src="https://github.com/aws-amplify/amplify-backend/assets/34548660/20782f33-7af2-4bab-9265-4c7f4f0af102">

Alternatively, if aws-cdk-lib / contructs are in fact installed as peerDeps, users technically don't need to install the library again, they should just be able to import from it/ use since it's installed as a peerDep.
So you could mention in the docs that users don't need to install these libs.
Personally, I prefer the ChakraUI approach, because importing from/ using a package one hasn't explicitly installed seems problematic.

**Comment by josefaidt** [comment]
Hey @brandoncroberts excellent callout, and yes this is something we're looking into to resolve the pain of installing peer deps with specific versions manually. 

> because importing from/ using a package one hasn't explicitly installed seems problematic.

While npm and yarn 1.x would resolve the phantom dependency, npm's `install-strategy=linked` and pnpm will fail to resolve if they are not also declared in your project's package.json. To mitigate this we're exploring adding aws-cdk-lib and constructs directly to your project on `npm create amplify`

**Comment by brandoncroberts** [comment]
> To mitigate this we're exploring adding aws-cdk-lib and constructs directly to your project on `npm create amplify`

I think that would be a good way to go!
I could it imagine it working in a similar way to Nx, and then when you want to upgrade amplify have like a `npx amplify migrate` command that updates the relevant packages.

**Comment by edwardfoyle** [comment]
done
