### ISSUE TITLE
`--dir-to-watch` to accept multiple directories

### ISSUE THREAD

**Issue by josefaidt** [aws-amplify/amplify-backend#652]
### Environment information

```plain text
System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 117.28 MB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.9.0 - ~/Library/Caches/fnm_multishells/77574_1680319338649/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/77574_1680319338649/bin/yarn
    npm: 10.2.1 - ~/Library/Caches/fnm_multishells/77574_1680319338649/bin/npm
    pnpm: 8.10.2 - ~/Library/Caches/fnm_multishells/77574_1680319338649/bin/pnpm
    bun: 1.0.6 - ~/.bun/bin/bun
    Watchman: Not Found
  npmPackages:
    @aws-amplify/backend: ^0.5.0 => 0.5.0 
    aws-amplify: ^6.0.2-unstable.a5eb335.0 => 6.0.2-unstable.a5eb335.0+a5eb335 
    aws-cdk: Not Found
    aws-cdk-lib: Not Found
    typescript: ^5.2.2 => 5.2.2
```

### Description

When working in a monorepo I may opt to write custom constructs or Functions outside of the workspace project I am writing my backend in. For example, I have my backend at `packages/my-backend` with the following `package.json` contents:

```json
{
  "name": "my-backend",
  "scripts": {
  	"dev": "amplify sandbox --dirs-to-watch ../pre-sign-up,../post-confirmation"
  }
}
```

or we can repeat the option

```json
{
  "name": "my-backend",
  "scripts": {
  	"dev": "amplify sandbox -w ../pre-sign-up -w ../post-confirmation"
  }
}
```

**Comment by edwardfoyle** [comment]
wontfix for now. Will address if there is additional customer feedback

**Comment by pmarkert** [comment]
+1 

I also ran into this, as I have a monorepo with an amplify project and a shared library that has used by other projects. There are lambda functions in my amplify project that import dependencies from the shared project. Ideally I would set the dirs-to-watch to the amplify directory and shared/src, but since it only allows one, I have to set the dir-to-watch to the parent ".." and then use exclusions to remove all of the other projects and subfolders of shared and the amplify project that shouldn't be watch. It works, but I'll have to update that list of exclusions each time I add a new folder or project to the monorepo. Would love to specifically "include" multiples.
